question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Entertainment: Television",
        "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
        "correct_answer": "True", "incorrect_answers": ["False"]
    },
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
     "question": "Nickelodeon rejected the pilot to Adventure Time.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                       "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Politics",
     "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Animals",
                                       "question": "You can tell the age of a ladybird by counting the spots on his back.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "An octopus can fit through any hole larger than its beak.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                       "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Art",
     "question": "Leonardo da Vinci was not the creator of the Mona Lisa.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                      "question": "California is larger than Japan.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                                       "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
     "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "Pete Townshend&#039;s solo album, &quot;White City: A Novel&quot;, is set in the metropolitan area of Chicago.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Board Games",
     "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
     "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
     "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "The average lifespan of a wildcat is only around 5-6 years. ", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                      "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "When BMW was established in 1916, it was producing automobiles.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                                      "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Nintendo started out as a playing card manufacturer.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                                       "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The game &quot;Battlefield 1&quot; takes place during World War I.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
     "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Tetris is the #1 best-selling video game of all-time.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Sports",
                                       "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
